// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SignalRAngularChat.Data.Entities
{
    public partial class Chat
    {
        public int ChatId { get; set; }
        public DateTime? Date { get; set; }
        public string Message { get; set; }
        public int UserId { get; set; }
        public int RoomId { get; set; }
        public string Type { get; set; }

        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}