// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SignalRAngularChat.Data.Entities;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SignalRAngularChat.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SignalRAngularChat.Data.Contexts
{
    public class RoomConfiguration : IEntityTypeConfiguration<Room>
    {
        public void Configure(EntityTypeBuilder<Room> entity)
        {
            entity.ToTable("Room");

            entity.HasIndex(e => e.RoomName)
                .HasName("UQ__Room__6B500B558C2ADB86")
                .IsUnique();

            entity.Property(e => e.RoomName)
                .HasMaxLength(255)
                .IsUnicode(false);
        }
    }
}
