// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SignalRAngularChat.Data.Entities;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SignalRAngularChat.Data.Entities;

namespace SignalRAngularChat.Data.Contexts
{
    public partial class SignalRAngularChatContext : DbContext
    {
        public SignalRAngularChatContext()
        {
        }

        public SignalRAngularChatContext(DbContextOptions<SignalRAngularChatContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomUser> RoomUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new ChatConfiguration());
            modelBuilder.ApplyConfiguration(new RoomConfiguration());
            modelBuilder.ApplyConfiguration(new RoomUserConfiguration());
            modelBuilder.ApplyConfiguration(new UserConfiguration());


            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
